"""One-shot export: apply GCPs to SITES_DATA (or picked_sites.json) and write GeoJSON + SQL.

Usage:
  python _export_sites.py                                         # hardcoded SITES_DATA
  python _export_sites.py --picked campsite_maps/picks.json       # from picker
  python _export_sites.py --picked picks.json --gcps my_gcps.json # custom GCPs
  python _export_sites.py --picked picks.json --sql migrations/027_my_camp.sql
"""
import argparse, json, numpy as np, re, os, sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)

ap = argparse.ArgumentParser()
ap.add_argument('--picked', default=None, help='Path to picked_sites.json')
ap.add_argument('--gcps',   default=os.path.join(_ROOT, 'Campsite Maps', 'overlay_gcps.json'),
                help='GCP JSON file (keys TL/TR/BR/BL with [lon,lat])')
ap.add_argument('--sql',    default=None, help='Override output SQL path')
ap.add_argument('--geojson',default=None, help='Override output GeoJSON path')
args = ap.parse_args()

if args.picked:
    with open(args.picked) as f:
        raw = json.load(f)
    SITES_DATA = [(p['name'], p['campground'], p['px'], p['py']) for p in raw]
    print(f'Using picked sites from {args.picked}')
else:
    sys.path.insert(0, _HERE)
    from ocr_campsites import SITES_DATA
    print('Using hardcoded SITES_DATA from ocr_campsites.py')

with open(args.gcps) as f:
    c = json.load(f)

iw, ih = 1105, 802
gcps = [(0,0,*c['TL']),(iw,0,*c['TR']),(iw,ih,*c['BR']),(0,ih,*c['BL'])]
A    = np.column_stack([[p[0] for p in gcps],[p[1] for p in gcps],np.ones(4)])
lons = np.array([p[2] for p in gcps])
lats = np.array([p[3] for p in gcps])
lc, *_ = np.linalg.lstsq(A, lons, rcond=None)
ac, *_ = np.linalg.lstsq(A, lats, rcond=None)

def p2g(px, py):
    v = np.array([px, py, 1.])
    return float(v @ lc), float(v @ ac)

features = []
for name, cg, px, py in SITES_DATA:
    lon, lat = p2g(px, py)
    stype    = 'electrical' if name.lower().endswith('e') else 'standard'
    num      = re.sub(r'[eE]$', '', name, flags=re.IGNORECASE)
    feat_name = 'Site ' + name.upper()
    osm_id    = 'campsite_site:' + cg[0].upper() + '-' + name.lower()
    features.append({
        'type': 'Feature',
        'geometry': {'type': 'Point', 'coordinates': [round(lon, 7), round(lat, 7)]},
        'properties': {
            '_osm_id':    osm_id,
            'name':       feat_name,
            'ref':        num,
            'campground': cg,
            'site_type':  stype,
        },
    })

out_dir = os.path.join(_ROOT, 'campsite_maps')
mig_dir = os.path.join(_ROOT, 'migrations')
os.makedirs(out_dir, exist_ok=True)
os.makedirs(mig_dir, exist_ok=True)

geojson_path = args.geojson or os.path.join(out_dir, 'quartzite_nl_sites.geojson')
sql_path     = args.sql     or os.path.join(mig_dir, '026_campsite_sites_data.sql')

with open(geojson_path, 'w') as f:
    json.dump({'type': 'FeatureCollection', 'features': features}, f, indent=2)

def sq(v): return str(v).replace("'", "''")

rows = [
    '-- Auto-generated by _export_sites.py',
    "delete from osm_geometries where source = 'campsite_sites';",
    '',
]
for feat in features:
    p    = feat['properties']
    ln   = feat['geometry']['coordinates'][0]
    la   = feat['geometry']['coordinates'][1]
    g    = f"st_setsrid(st_makepoint({ln},{la}),4326)"
    ps   = json.dumps(p).replace("'", "''")
    site_name = sq(p['name'])
    rows.append(
        f"insert into osm_geometries (source,name,geometry,properties) values "
        f"('campsite_sites','{site_name}',{g},'{ps}'::jsonb);"
    )

with open(sql_path, 'w') as f:
    f.write('\n'.join(rows) + '\n')

q  = sum(1 for ft in features if ft['properties']['campground'] == 'quartzite')
nl = sum(1 for ft in features if ft['properties']['campground'] == 'northern_lights')
print(f'Generated {len(features)} sites  (Q={q}  NL={nl})')
print(f'  {geojson_path}')
print(f'  {sql_path}')
